---
apiVersion: v1
kind: Namespace
metadata:
  name: dex
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dex-secrets
  namespace: dex
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: dex-secrets
  data:
    - secretKey: KUBERO_CLIENT_SECRET
      remoteRef:
        key: kubero_client_secret
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: dex
  namespace: dex
spec:
  interval: 5m
  url: https://charts.dexidp.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dex
  namespace: dex
spec:
  releaseName: dex
  chart:
    spec:
      chart: dex
      version: 0.23.0
      sourceRef:
        kind: HelmRepository
        name: dex
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    config:
      issuer: https://sso.zozo.pro.br/dex

      storage:
        type: sqlite3
        config:
          file: /var/dex/dex.db

      enablePasswordDB: true

      staticPasswords:
      - email: "thiago@tao.tec.br"
        hash: "$2a$12$1hy8GxbjFcw6RXm7A89hhOGrQDDYJ6DkNQkFIeNVqOShtJuuZmsvm"
        username: "zozo"
        userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"

      staticClients:
      - id: kubero
        redirectURIs:
        - 'https://kubero.zozo.pro.br/api/auth/oauth2/callback'
        name: 'Kubero'
        secretEnv: KUBERO_CLIENT_SECRET

    envFrom:
    - secretRef:
        name: dex-secrets

    persistence:
      enabled: true
      storageClassName: "local-path"
      accessModes:
        - ReadWriteOnce
      size: 1Gi

    ingress:
      enabled: true
      className: traefik
      annotations:
        cert-manager.io/cluster-issuer: cloudflare
        external-dns.alpha.kubernetes.io/target: 137.131.161.90
      hosts:
        - host: sso.zozo.pro.br
          paths:
        - path: /
          pathType: ImplementationSpecific
      tls:
        - secretName: dex-tls
          hosts:
            - sso.zozo.pro.br