---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets-controller
  namespace: flux-system
spec:
  interval: 5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./addons/external-secrets/controller
  prune: true
  wait: true
  timeout: 5m0s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets-configs
  namespace: flux-system
spec:
  dependsOn:
    - name: external-secrets-controller
  interval: 5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./addons/external-secrets/configs
  prune: true
  wait: true
  timeout: 5m0s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tailscale
  namespace: flux-system
spec:
  dependsOn:
    - name: external-secrets-controller
    - name: external-secrets-configs
  interval: 5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./addons/tailscale
  prune: true
  wait: true
  timeout: 5m0s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-dns
  namespace: flux-system
spec:
  dependsOn:
    - name: external-secrets-controller
    - name: external-secrets-configs
  interval: 5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./addons/external-dns
  prune: true
  wait: true
  timeout: 5m0s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  dependsOn:
    - name: tailscale
  interval: 5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./addons/ingress-nginx
  prune: true
  wait: true
  timeout: 5m0s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-controller
  namespace: flux-system
spec:
  dependsOn:
    - name: external-secrets-controller
    - name: external-secrets-configs
    - name: ingress-nginx
  interval: 5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./addons/cert-manager/controller
  prune: true
  wait: true
  timeout: 5m0s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-configs
  namespace: flux-system
spec:
  dependsOn:
    - name: cert-manager-controller
  interval: 5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./addons/cert-manager/configs
  prune: true
  wait: true
  timeout: 5m0s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dex
  namespace: flux-system
spec:
  dependsOn:
    - name: external-secrets-controller
    - name: external-secrets-configs
  interval: 5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./addons/dex
  prune: true
  wait: true
  timeout: 5m0s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubero-operator
  namespace: flux-system
spec:
  dependsOn:
    - name: cert-manager-controller
    - name: cert-manager-configs
    - name: external-dns
    - name: ingress-nginx
    - name: tailscale
  interval: 5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./addons/kubero/kubero-operator
  prune: true
  wait: true
  timeout: 5m0s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubero-prometheus
  namespace: flux-system
spec:
  dependsOn:
    - name: cert-manager-controller
    - name: cert-manager-configs
    - name: external-dns
    - name: ingress-nginx
    - name: tailscale
    - name: kubero-operator
  interval: 5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./addons/kubero/kubero-prometheus
  prune: true
  wait: true
  timeout: 5m0s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubero-ui
  namespace: flux-system
spec:
  dependsOn:
    - name: cert-manager-controller
    - name: cert-manager-configs
    - name: external-dns
    - name: ingress-nginx
    - name: tailscale
    - name: kubero-operator
    - name: kubero-prometheus
  interval: 5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./addons/kubero/kubero-ui
  prune: true
  wait: true
  timeout: 5m0s
