---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metrics-server
  namespace: flux-system
spec:
  interval: 5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./addons/metrics-server
  prune: true
  wait: true
  timeout: 5m0s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets-controller
  namespace: flux-system
spec:
  interval: 5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./addons/external-secrets/controller
  prune: true
  wait: true
  timeout: 5m0s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets-configs
  namespace: flux-system
spec:
  dependsOn:
    - name: external-secrets-controller
  interval: 5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./addons/external-secrets/configs
  prune: true
  wait: true
  timeout: 5m0s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tailscale
  namespace: flux-system
spec:
  dependsOn:
    - name: external-secrets-controller
    - name: external-secrets-configs
  interval: 5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./addons/tailscale
  prune: true
  wait: true
  timeout: 5m0s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-dns
  namespace: flux-system
spec:
  dependsOn:
    - name: external-secrets-controller
    - name: external-secrets-configs
  interval: 5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./addons/external-dns
  prune: true
  wait: true
  timeout: 5m0s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  dependsOn:
    - name: tailscale
  interval: 5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./addons/ingress-nginx
  prune: true
  wait: true
  timeout: 5m0s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-controller
  namespace: flux-system
spec:
  dependsOn:
    - name: external-secrets-controller
    - name: external-secrets-configs
    - name: ingress-nginx
  interval: 5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./addons/cert-manager/controller
  prune: true
  wait: true
  timeout: 5m0s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-configs
  namespace: flux-system
spec:
  dependsOn:
    - name: cert-manager-controller
  interval: 5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./addons/cert-manager/configs
  prune: true
  wait: true
  timeout: 5m0s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
spec:
  dependsOn:
    - name: ingress-nginx
    - name: cert-manager-configs
  interval: 5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./addons/kube-prometheus-stack
  prune: true
  wait: true
  timeout: 5m0s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cnpg
  namespace: flux-system
spec:
  interval: 5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./addons/cnpg
  prune: true
  wait: true
  timeout: 5m0s