---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets-secret-store
  namespace: external-secrets
spec:
  dependsOn:
    - name: external-secrets
      kind: HelmRelease
  interval: 5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./secret-store
  prune: true
  wait: true
  timeout: 5m0s
