apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tailscale-auth
  namespace: tailscale
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: tailscale-auth
  data:
    - secretKey: values.yaml
      remoteRef:
        key: tailscale_values