
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale
  namespace: tailscale
spec:
  releaseName: tailscale
  dependsOn:
    - name: external-secrets
      kind: HelmRelease
  chart:
    spec:
      chart: tailscale
      version: 1.82.0
      sourceRef:
        kind: HelmRepository
        name: tailscale
  interval: 5m
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: Secret
      name: tailscale-auth
