---
apiVersion: v1
kind: Namespace
metadata:
  name: vela-system
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kubevela
  namespace: vela-system
spec:
  interval: 5m
  url: https://kubevela.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kubevela
  namespace: vela-system
spec:
  releaseName: kubevela
  chart:
    spec:
      chart: vela-core
      version: 1.10.3
      sourceRef:
        kind: HelmRepository
        name: kubevela
  interval: 5m
  install:
    remediation:
      retries: 3
