---
apiVersion: v1
kind: Namespace
metadata:
  name: cnpg-system
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cnpg
  namespace: cnpg-system
spec:
  interval: 5m
  url: https://cloudnative-pg.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg
  namespace: cnpg-system
spec:
  releaseName: cnpg
  chart:
    spec:
      chart: cnpg/cloudnative-pg
      version: 0.24.0
      sourceRef:
        kind: HelmRepository
        name: cnpg
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    monitoring:
      grafanaDashboard:
        create: true
        namespace: monitoring
      podMonitorEnabled: true